oxygen: sepolicy: Label qcom extcon sysfs
Log:
W/ExtconUEventObserver Unable to read /sys/devices/platform/soc/200f000.qcom,spmi/spmi-0/spmi0-02/200f000.qcom,spmi:qcom,pmi8950@2:qcom,qpnp-smbcharger/extcon/extcon1/cable.0/name. This probably means the selinux policies need to be changed.
java.io.FileNotFoundException: /sys/class/extcon/extcon1/cable.0/name: open failed: EACCES (Permission denied)

W/ExtconUEventObserver Unable to read /sys/devices/platform/soc/soc:qcom,mdss_wb_panel/extcon/extcon0/cable.0/name. This probably means the selinux policies need to be changed.
java.io.FileNotFoundException: /sys/class/extcon/extcon0/cable.0/name: open failed: EACCES (Permission denied)

Change-Id: c5ae58b9a7f85772e0c21fb45c470ca2e226f409
Signed-off-by: TogoFire <italomellopereira@gmail.com>